[package]
name = "skui_masonry_macro"
version = "0.1.0"
license = "MIT"
description = "derive impls for masonry"
repository = "https://github.com/markijohn/druid-xml"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"