[package]
name = "skui"
version = "0.1.0"
authors = ["markijohn <kitae.john@gmail.com>"]
edition = "2024"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[dependencies]
logos = "0.16.0"
thiserror = "2.*"

[lib]
name = "skui"
path = "src/lib.rs"